commit for cloud watch

diff --git a/.github/workflows/packerchecks.yml b/.github/workflows/packerchecks.yml
--- a/.github/workflows/packerchecks.yml
+++ b/.github/workflows/packerchecks.yml
@@ -47,16 +47,12 @@ jobs:
         run: |
           cd ./packer
           packer init .
-          packer fmt ./ami.pkr.hcl
-          # Check the exit code of the previous command
-          if [ $? -ne 0 ]; then
-              echo "Error: Packer format failed. Please ensure your configuration file is correctly formatted."
-              exit 1
+          if ! packer fmt -check ./packer/aws-debian.pkr.hcl; then
+           echo "Packer format check failed"
+           exit 1
           fi
 
-          packer validate ./ami.pkr.hcl
-          # Check the exit code of the previous command
-          if [ $? -ne 0 ]; then
-              echo "Error: Packer validation failed. Please check your Packer configuration file for any errors."
-              exit 1
+          if ! packer validate ./packer/aws-debian.pkr.hcl; then
+            echo "Packer validate failed"
+            exit 1
           fi
